# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: |
        git submodule
        git submodule update --init --recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Bukkit with Maven
      run: mvn package --file ./BongeBukkit/pom.xml
    - name:
      run: mkdir "target/classes"
    - name: Copy Bukkit to target
      run: cp -R "BongeBukkit/target/classes" "target/classes"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: "Bonge"
        path: "target/*-shaded.jar"

